### ISSUE TITLE
Hello, glad the latest version worked. Some of the AWS API responses changed and broke one of the original scripts. As you discovered, the latest version in the repo fixed that issue. I'll get the older copy you found updated to the latest version.

### ISSUE THREAD

**Issue by Joemamvong** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#19]
I tried cloning the repo and could not even get passed running the:

ca_create_signer_csr.py
anymore. 

PS C:\Users\Joema\OneDrive\Desktop\zt_master_clone\aws-iot-zero-touch-secure-provisioning-kit> python ca_create_signer_csr.py

Loading signer CA key
    No key file found, generating new key
    Saving to signer-ca.key

Generating signer CA CSR
Traceback (most recent call last):
  File "ca_create_signer_csr.py", line 78, in <module>
    ca_create_signer_csr()
  File "ca_create_signer_csr.py", line 21, in ca_create_signer_csr
    public_key=signer_ca_priv_key.public_key())
  File "ca_create_signer_csr.py", line 70, in add_signer_extensions
    x509.AuthorityKeyIdentifier.from_issuer_subject_key_identifier(subj_key_id_ext.value),
  File "C:\Users\Joema\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\x509\extensions.py", line 192, in from_issuer_subject_key_identifier
    key_identifier=ski.value.digest,
AttributeError: 'SubjectKeyIdentifier' object has no attribute 'value'
PS C:\Users\Joema\OneDrive\Desktop\zt_master_clone\aws-iot-zero-touch-secure-provisioning-kit>

In the earlier version of the kit, this didn't have any issue> Ben could you kindly verify the functionality of the current codes in the kit? This would be very helpful. Thanks for the effort.

**Comment by Joemamvong** [comment]
Hello Ben,
I am having thesame issue as you stated here provisoning this device at the moment. I still do not understand how I can resolve this or get passed it. Can you kindly advice me on how I can resolve this? here is the error i keep getting:

Getting CA registration code from AWS IoT
Traceback (most recent call last):
File "aws_register_signer.py", line 121, in
aws_register_signer(aws_profile=args.profile)
File "aws_register_signer.py", line 54, in aws_register_signer
reg_code = aws_iot.get_registration_code()['registrationCode']
File "C:\Users\Joema\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "C:\Users\Joema\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetRegistrationCode operation: The security token included in the request is invalid.

Kindly advise me on how I can resolve this please. Thanks.

Regards,
