### ISSUE TITLE
TypeError running ca_create_root.py

### ISSUE THREAD

**Issue by sandeepmistry** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#4]
I'm using the master version of this repo in a Ubuntu 16.04 VM, which has Python 3.5.2 installed and ran `pip3 install -r requirements.txt ` to get the dependencies.

```
$ python3 ca_create_root.py 

Loading root CA key
    No key file found, generating new key
    Saving to root-ca.key

Generating self-signed root CA certificate
Traceback (most recent call last):
  File "ca_create_root.py", line 51, in <module>
    main()
  File "ca_create_root.py", line 27, in main
    builder = builder.not_valid_before(datetime.datetime.now(tz=pytz.utc))
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 441, in not_valid_before
    if time <= _UNIX_EPOCH:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by sandeepmistry** [comment]
Things are working with the following changes:

```
$ git diff
diff --git a/ca_create_root.py b/ca_create_root.py
index 69c7307..4f36f76 100644
--- a/ca_create_root.py
+++ b/ca_create_root.py
@@ -24,7 +24,7 @@ def main():
     builder = builder.issuer_name(x509.Name([
         x509.NameAttribute(x509.oid.NameOID.ORGANIZATION_NAME, u'Example Inc'),
         x509.NameAttribute(x509.oid.NameOID.COMMON_NAME, u'Example Root CA')]))
-    builder = builder.not_valid_before(datetime.datetime.now(tz=pytz.utc))
+    builder = builder.not_valid_before(datetime.datetime.now())
     builder = builder.not_valid_after(builder._not_valid_before.replace(year=builder._not_valid_before.year + 25))
     builder = builder.subject_name(builder._issuer_name)
     builder = builder.public_key(root_ca_priv_key.public_key())
```

**Comment by sandeepmistry** [comment]
After upgrading my cryptography package to the latest, the original file works. I would suggest pinning a mime version in the requirements.txt.

https://github.com/pyca/cryptography/blob/d6ad9fd2e05b70f5d01a3cbee7f97624abbaddbc/CHANGELOG.rst#13---2016-03-18

**Comment by BenUdall-Microchip** [comment]
Thank you for the notification. I'll add a minimum version to the cryptography package in requirements.txt
