### ISSUE TITLE
kit_provision.py error

### ISSUE THREAD

**Issue by riteshSTPL** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#6]
I have followed all the step as per the guide http://microchipdeveloper.com/iot:ztpk

But kit_provision.py gives me following error
```
Opening AWS Zero-touch Kit Device
Traceback (most recent call last):
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\kit_provision.py", line 147, in <module>
    main()
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\kit_provision.py", line 27, in main
    device.open()
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\mchp_aws_zt_kit.py", line 24, in open
    return self.device.open(vendor_id, product_id)
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed
```

I am getting driver detected with following VID & PID. So i updated in 'mchp_aws_zt_kit.py'.
DEVICE_HID_VID = 0x03eb
DEVICE_HID_PID = 0x2111
After updating i am getting below error.

```
Opening AWS Zero-touch Kit Device

Initializing Kit
Traceback (most recent call last):
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\kit_provision.py", line 147, in <module>
    main()
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\kit_provision.py", line 30, in main
    resp = device.init()
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\mchp_aws_zt_kit.py", line 102, in init
    resp = self.kit_read_app_no_error(id)
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\mchp_aws_zt_kit.py", line 94, in kit_read_app_no_error
    resp = self.kit_read_app(id)
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\mchp_aws_zt_kit.py", line 81, in kit_read_app
    kit_resp = self.parse_kit_reply(data)
  File "D:\Projects\Liquitech\AtmelAWS\Software\aws-iot-zero-touch-secure-provisioning-kit-master\mchp_aws_zt_kit.py", line 74, in parse_kit_reply
    raise ValueError('Unable to parse kit protocol reply: %s' % data)
ValueError: Unable to parse kit protocol reply: ÿ  ♠♫
```
What is the issue in my case?

**Comment by Maryam-Maya-Karimi** [comment]
I had the same issue for hours, I changed my usb cables and it is resolved.
