### ISSUE TITLE
the security token included in the request is invalid

### ISSUE THREAD

**Issue by JelleB** [MicrochipTech/aws-iot-zero-touch-secure-provisioning-kit#7]
Hi,

just followed the ztpk guide, but hit a snag when running the aws_register_signer.py command. The error is: 
Getting CA registration code from AWS IoT
Traceback (most recent call last):
  File "C:\Users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_register_signer.py", line 119, in <module>
    main()
  File "C:\Users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_register_signer.py", line 64, in main
    reg_code = aws_iot.get_registration_code()['registrationCode']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\botocore\client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetRegistrationCode operation: The security token included in the request is invalid.

that was the initial error..: after trying again but this time in powershell (instead of cmd.exe),  the script gets further, but fails at save_kit_info:
Getting AWS IoT device endpoint
    Hostname: a10nbthkpnvvpf.iot.eu-central-1.amazonaws.com
Traceback (most recent call last):
  File "C:\users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_register_signer.py", line 119, in <module>
    main()
  File "C:\users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_register_signer.py", line 114, in main
    save_kit_info(kit_info)
  File "C:\users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_kit_common.py", line 42, in save_kit_info
    f.write(json.dumps(kit_info, indent=4, sort_keys=True))
  File "C:\Program Files (x86)\Python36-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\Program Files (x86)\Python36-32\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'datetime' is not JSON serializable

this probably writes somethis incorrectly to file, as subsequent runs of the command get an error in File "C:\users\Jelle\Zign\tls-gedoe\aws-iot-zero-touch-kit-20170926\aws_register_signer.py", line 27, in main
    kit_info = read_kit_info()

**Comment by JelleB** [comment]
nevermind, I spoke too soon. The guide points to a snapshot of the repo, but cloning the repo itself works without a hitch.

**Comment by BenUdall-Microchip** [comment]
Hello, glad the latest version worked. Some of the AWS API responses changed and broke one of the original scripts. As you discovered, the latest version in the repo fixed that issue. I'll get the older copy you found updated to the latest version.

**Comment by Joemamvong** [comment]
Hello Ben, 
I am having thesame issue as you stated here provisoning this device at the moment. I still do not understand how I can resolve this or get passed it. Can you kindly advice me on how I can resolve this? here is the error i keep getting:

Getting CA registration code from AWS IoT
Traceback (most recent call last):
  File "aws_register_signer.py", line 121, in <module>
    aws_register_signer(aws_profile=args.profile)
  File "aws_register_signer.py", line 54, in aws_register_signer
    reg_code = aws_iot.get_registration_code()['registrationCode']
  File "C:\Users\Joema\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Joema\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetRegistrationCode operation: The security token included in the request is invalid.

Kindly advise me on how I can resolve this please. Thanks.

Regards,
